# Generated by Django 6.0 on 2025-12-31 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_category_material_product_category_product_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='artisanprofile',
            name='profile_image',
            field=models.ImageField(blank=True, default='artisans/default.png', null=True, upload_to='artisans/'),
        ),
    ]
