# Generated by Django 6.0 on 2026-01-03 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_product_is_active_product_is_out_of_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artisanprofile',
            name='profile_image',
            field=models.ImageField(blank=True, default='images/user-default.png', null=True, upload_to='artisans/'),
        ),
    ]
