# Generated by Django 6.0 on 2026-01-03 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_alter_artisanprofile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artisanprofile',
            name='profile_image',
            field=models.ImageField(blank=True, default='artisans/user-default.png', null=True, upload_to='artisans/'),
        ),
    ]
